name: npm-build
on: 
  push:
    branches: [main]
  pull_request:
    
jobs:
  start:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - run: echo "Running npm start..........."
      - run: npm start

  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - run: echo "Running npm test................"
      - run: npm install
      - run: npm test
