name: secret-fetch
on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Test stage"
      - run: echo "Test Stage Complete!!!!!"


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Running Deploy stage"
      - run: echo "Deploy completed"
