name: secret-fetch
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Test stage"
      - run: echo "Test Stage Complete!!!!!"


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Running Deploy stage"
      - run: echo "Fetching Secret value of API_KEY : ${{ secrets.API_KEY }}"
      - run: echo "Deploy completed"
